"""add ticket counter and entry constraints

Revision ID: 28c13e1939e7
Revises: 4ce260c7c345
Create Date: 2026-10-01 23:37:32.243507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c13e1939e7'
down_revision: Union[str, Sequence[str], None] = '4ce260c7c345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_queue_entries_active_user', 'queue_entries', ['queue_id', 'user_id'], unique=True, postgresql_where=sa.text('status IN (1, 2)'))
    op.create_unique_constraint('uq_queue_entries_queue_ticket', 'queue_entries', ['queue_id', 'ticket_number'])
    op.add_column('queues', sa.Column('next_ticket_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'next_ticket_number')
    op.drop_constraint('uq_queue_entries_queue_ticket', 'queue_entries', type_='unique')
    op.drop_index('uq_queue_entries_active_user', table_name='queue_entries', postgresql_where=sa.text('status IN (1, 2)'))
    # ### end Alembic commands ###
