"""add outbox events table

Revision ID: f5b12cde7e69
Revises: 28c13e1939e7
Create Date: 2026-10-10 14:42:11.828025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5b12cde7e69'
down_revision: Union[str, Sequence[str], None] = '28c13e1939e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('message_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['id'], unique=False, postgresql_where=sa.text('published_at IS NULL'), sqlite_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'), sqlite_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
